class SilvioComentario {

    static comentarios = [
        {estilo: 'Romântico',           comentario: 'mande pro seu amorm!'},
        {estilo: 'Alternativo',         comentario: 'música de Hipster chatom!'},
        {estilo: 'Axé',                 comentario: 'ritmom de carnaval!'},
        {estilo: 'Blues',               comentario: 'vocês estão sofrendom?'},
        {estilo: 'Bolero',              comentario: 'o ritmo da paixão Maestrom!'},
        {estilo: 'Bossa Nova',          comentario: 'essa é do meu tempo Maestrom!'},
        {estilo: 'Brega',               comentario: 'é do Calypsomm? Toca aí Maestrom!'},
        {estilo: 'Clássico',            comentario: 'essa é das boas, toca ai Maestrom!'},
        {estilo: 'Country',             comentario: 'só os cowboys de rodeiom!'},
        {estilo: 'Dance',               comentario: 'é ritmom de festam!'},
        {estilo: 'Disco',               comentario: 'é ritmom de festam!'},
        {estilo: 'Eletrônica',          comentario: 'é ritmom de festa com muita droga Maestrom!'},
        {estilo: 'Emocore',             comentario: 'esconde as navalhas Leminham!'},
        {estilo: 'Fado',                comentario: 'que saudade de Portugalm'},
        {estilo: 'Folk',                comentario: 'que diabos é isso Maestrom?'},
        {estilo: 'Forró',               comentario: 'o ritmom de festa pra dança agarradom!'},
        {estilo: 'Funk',                comentario: 'desce e sobe a rabam Maestrom!'},
        {estilo: 'Gospel/Religioso',    comentario: 'essa é pra se arrepender dos pecados Maestrom!'},
        {estilo: 'Gótico',              comentario: 'essa é pra montar o pentagrama invertidom na salam e chamar o satanás!'},
        {estilo: 'Grunge',              comentario: 'música de drogado suicída Maestrom!'},
        {estilo: 'Hard Rock',           comentario: 'essa é bem xexelentam!'},
        {estilo: 'Hardcore',            comentario: 'essa é pauleram Maestrom!'},
        {estilo: 'Heavy Metal',         comentario: 'essa música é do demôniom!'},
        {estilo: 'Hip Hop/Rap',         comentario: 'me traz o boné de aba reta Leminham!'},
        {estilo: 'House',               comentario: 'essa música é de fritadom, toca ai Maestrom!'},
        {estilo: 'Indie',               comentario: 'essa música é de Hipster chatom!'},
        {estilo: 'Infantil',            comentario: 'essa é aquela da Maísa Leminham?'},
        {estilo: 'J-Pop/J-Rock',        comentario: 'direto do outro lado do planetam'},
        {estilo: 'Jazz',                comentario: 'aahh essa é das boas'},
        {estilo: 'Jovem Guarda',        comentario: 'que saudadem!'},
        {estilo: 'K-Pop/K-Rock',        comentario: 'essa é aquela música dos jovemsm'},
        {estilo: 'Mariachi',            comentario: 'traz a tequila Leminham!'},
        {estilo: 'Merengue',            comentario: 'traz a tequila Leminham!'},
        {estilo: 'MPB',                 comentario: 'música boamm!'},
        {estilo: 'Pagode',              comentario: 'é ritmo de festamm!'},
        {estilo: 'Pop Rock',            comentario: 'o roque sem sal!'},
        {estilo: 'Pop',                 comentario: 'essa é aquela que fez sucesso Leminham?'},
        {estilo: 'Post-Rock',           comentario: 'mas que diabo é isso Maestrom?'},
        {estilo: 'Power-Pop',           comentario: 'mas que diabo é isso Maestrom?'},
        {estilo: 'Rock Progressivo',    comentario: 'traz o LSD Leminham!'},
        {estilo: 'Psicodelia',          comentario: 'traz o LSD Leminham!'},
        {estilo: 'Punk Rock',           comentario: 'essa é aquela que os jovems quebram tudo Leminham?'},
        {estilo: 'Reggae',              comentario: 'traz o verde Leminham!'},
        {estilo: 'Reggaeton',           comentario: 'traz o verde Leminham e vamo dançarm!'},
        {estilo: 'Rock',                comentario: 'é o roquem!'},
        {estilo: 'Salsa',               comentario: 'dançandom e rodandom!'},
        {estilo: 'Samba',               comentario: 'é ritmo de carnaval Leminham!'},
        {estilo: 'Sertanejo',           comentario: 'é de afia o chifre no asfalto Leminham!'},
        {estilo: 'Velha Guarda',        comentario: 'éssa meu vô escutavam!'}

    ];
}
module.exports = SilvioComentario;